name: fitnest
description: "FitNest is an innovative mobile application designed to bring sports enthusiasts together and simplify the organization of sporting activities. Whether you're a runner, cyclist, football lover, or engaged in any other sport, FitNest allows you to meet like-minded individuals and participate in local sporting events."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http:
  dio:
  intl:
  logger:
  lottie:
  url_launcher:
  connectivity_plus: ^5.0.1
  flutter_native_splash:
  smooth_page_indicator:
  shimmer:
  dynamic_multi_step_form:
  iconsax:
  cupertino_icons:
  fl_chart: ^0.62.0
  animated_toggle_switch: ^0.6.2
  simple_animation_progress_bar: ^1.6.0
  simple_circular_progress_bar: ^1.0.2
  dotted_dashed_line: ^0.0.3
  google_maps_flutter:
  readmore: ^2.1.0
  image_picker:
  flutter_map: ^4.0.0
  flutter_map_marker_cluster: ^1.1.1
  geolocator: ^13.0.1
  latlong2: ^0.8.0
  flutter_google_places: ^0.3.0
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.1
  flutter_staggered_animations: ^1.1.1
  flutter_tesseract_ocr:
  json_annotation:
  image:
  flutter_image_compress:

  # State Management
  get:
  get_storage:

 #for notifications

  firebase_core:
  firebase_messaging:
  googleapis_auth:
  googleapis:
  fluttertoast: ^8.2.8
  permission_handler: ^11.1.0
  flutter_local_notifications:

#----------------------- ./ PACKAGES END ----------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1
  build_runner:
  json_serializable:

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/FN-logo.png"



flutter:


  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/on-boarding-images/
    - assets/images/animations/
    - assets/images/static-images/
    - assets/icons/
    - assets/images/



#----------------------- LOCAL FONTS ---------------------------#
fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
        weight: 300
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 800
